// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    error: Error_.Error_;
}

export namespace Error_ {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            Unauthenticated: "UNAUTHENTICATED",
            InvalidRequest: "INVALID_REQUEST",
            NotFound: "NOT_FOUND",
            InvalidState: "INVALID_STATE",
            Conflict: "CONFLICT",
            RateLimited: "RATE_LIMITED",
            Internal: "INTERNAL",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
