// This file was auto-generated by Fern from our API Definition.

/**
 * Metered admission refused the create/start: the balance is not positive. Top up first.
 */
export interface InsufficientBalanceError {
    error: InsufficientBalanceError.Error_;
}

export namespace InsufficientBalanceError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            InsufficientBalance: "INSUFFICIENT_BALANCE",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
