// This file was auto-generated by Fern from our API Definition.

/**
 * A limit refused the request — `code` names which: RATE_LIMITED = request-rate budget (wait `Retry-After`, retry); CONCURRENCY_LIMIT = the running-runtime cap (a quota — destroy a runtime or raise the cap; retrying without that cannot succeed, and no Retry-After is sent); RESOURCE_QUOTA = a per-family vCPU/memory ceiling would be passed (resource-governance Gate C) or the team's total provisioned-storage entitlement would be passed; release the named resource or raise its entitlement (no Retry-After).
 */
export interface LimitExceededError {
    error: LimitExceededError.Error_;
}

export namespace LimitExceededError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            RateLimited: "RATE_LIMITED",
            ConcurrencyLimit: "CONCURRENCY_LIMIT",
            ResourceQuota: "RESOURCE_QUOTA",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
