// This file was auto-generated by Fern from our API Definition.

/**
 * The requested location cannot take this runtime right now — its cluster is full, draining, or not yet live. No row, PVC, or charge is created; retry later or pick another region (GET /v1/regions). Never a silent cross-location fallback.
 */
export interface NoCapacityError {
    error: NoCapacityError.Error_;
}

export namespace NoCapacityError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            NoCapacity: "NO_CAPACITY",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
