// This file was auto-generated by Fern from our API Definition.

/**
 * Absent until the engine records its first observation — normally within a few seconds of create. Absence means "not yet observed", never an error.
 */
export interface Observed {
    /** Engine-observed lifecycle phase. Convergence deadline: a runtime that stays `provisioning` for 5 minutes (300 000 ms) without coming healthy flips to `error` — pull failures, crash loops, and workloads that never pass readiness all surface this way. `error` is not terminal: the engine keeps reconciling, and a workload that later comes healthy returns to `running`. */
    phase: Observed.Phase;
    /** The desired generation this reflects. */
    generation: number;
    lastSeen: string;
    /** Workload container restart count. Absent until compute has been observed. A climbing count while phase sits at `provisioning` means the workload is crashing at boot — a workload problem, not a provisioning delay. */
    restarts?: number | undefined;
    /** The workload container's last terminal exit. Absent while it has never died. This is the WHY behind a crash loop — read it before filing a provisioning issue. */
    lastExit?: Observed.LastExit | undefined;
}

export namespace Observed {
    /** Engine-observed lifecycle phase. Convergence deadline: a runtime that stays `provisioning` for 5 minutes (300 000 ms) without coming healthy flips to `error` — pull failures, crash loops, and workloads that never pass readiness all surface this way. `error` is not terminal: the engine keeps reconciling, and a workload that later comes healthy returns to `running`. */
    export const Phase = {
        Provisioning: "provisioning",
        Running: "running",
        Stopped: "stopped",
        Error: "error",
        Destroying: "destroying",
        Destroyed: "destroyed",
    } as const;
    export type Phase = (typeof Phase)[keyof typeof Phase];

    /**
     * The workload container's last terminal exit. Absent while it has never died. This is the WHY behind a crash loop — read it before filing a provisioning issue.
     */
    export interface LastExit {
        /** Coarse terminal label (`Error`, `OOMKilled`, …) — stable vocabulary, not prose. */
        reason: string;
        exitCode: number | null;
        /** When the container last exited (ISO-8601), if known. */
        at: string | null;
    }
}
