// This file was auto-generated by Fern from our API Definition.

/**
 * The request body exceeds the wire-level bound (512 KiB on the exec routes) — refused before parsing. The stdin field has its own 256 KiB cap inside this bound (400).
 */
export interface PayloadTooLargeError {
    error: PayloadTooLargeError.Error_;
}

export namespace PayloadTooLargeError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            InvalidRequest: "INVALID_REQUEST",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
