// This file was auto-generated by Fern from our API Definition.

/**
 * New allocation is temporarily unavailable because placement has no capacity, billing catch-up is incomplete, or the image registry is unavailable. Nothing is provisioned or charged; retry later.
 */
export interface ProvisioningUnavailableError {
    error: ProvisioningUnavailableError.Error_;
}

export namespace ProvisioningUnavailableError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            NoCapacity: "NO_CAPACITY",
            BillingNotReady: "BILLING_NOT_READY",
            RegistryUnavailable: "REGISTRY_UNAVAILABLE",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
