// This file was auto-generated by Fern from our API Definition.

/**
 * The team already holds a credential for this registry host — at most one per host (matching stays deterministic). Rotate or delete the existing credential instead.
 */
export interface RegistryHostExistsError {
    error: RegistryHostExistsError.Error_;
}

export namespace RegistryHostExistsError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            RegistryHostExists: "REGISTRY_HOST_EXISTS",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
