// This file was auto-generated by Fern from our API Definition.

export interface RegionFamilyAvailability {
    /** A preset family offered at this location (see GET /v1/presets). */
    family: string;
    /** Whether at least one cluster at this location can take the family's smallest preset right now. `false` = full, draining, or not yet commissioned — a create naming this location refuses 503 until it flips. Derived live on every read; re-read rather than remember. */
    available: boolean;
}
