// This file was auto-generated by Fern from our API Definition.

/**
 * Optional resource allocation. Omitted = the published defaults: 1 vCPU (cpuMillis 1000), 2 GiB memoryBytes (2147483648), 4 GiB storageBytes (4294967296). Reads always echo the effective (defaults-applied) values.
 */
export interface ResourceSpecInput {
    /** RAM allocation in bytes. Minimum 134217728 (128 MiB) — below that no real image starts, so sub-floor requests are rejected here instead of surfacing as a confusing in-guest OOM after boot. */
    memoryBytes: number;
    /** CPU allocation in millicores (1000 = 1 vCPU). */
    cpuMillis: number;
    /** Persistent volume size in bytes. The volume is mounted read-write at `/data` inside the workload; it survives stop/start and follows the runtime for life. Durability: every volume is backed up daily to off-site object storage — 7-day retention. Backups are crash-consistent disaster-recovery copies: a restore point is normally under 24 hours old and never silently older than 26 hours — past that the platform raises an alarm. Keep your own backups of critical data. Restore is on request today and arrives as a NEW volume (self-serve restore is planned). Volumes are not live-replicated. Writable by the workload's own user, whatever the image runs as — root or not, no setup needed: the volume root arrives group-writable to a platform group the workload process automatically carries as a supplementary group. Files the workload creates keep their normal ownership. Software that demands strict permissions on its data directory (e.g. PostgreSQL's initdb) should use a subdirectory and set its own mode (`mkdir -m 700 /data/pgdata`). This is the only metered disk. Optional at create: omitted → the 4 GiB default (4294967296), or — with `volumeId` — the attached volume's own size. Mutually exclusive with `volumeId` (400 when both are present). Reads always echo the effective value. */
    storageBytes?: number | undefined;
    /** Rootfs scratch-disk budget in bytes. The rootfs is a real block disk of a fixed tier size (4 or 8 GiB); the ask rounds UP to the smallest tier that fits, and `df /` inside the workload reports that tier honestly. Persistence follows `preserveRootfs` (default true): `stop` commits the disk and the next `start` resumes it. Any OTHER restart — a crash, or a config/env change that recreates the workload — begins from the last committed image (the original image if it has never been stopped), so writes since that boot are lost. Durable data belongs on `/data`, which is unaffected either way. Bundled, never billed. Omitted → 4 GiB default. Free up to the 8 GiB cap; above the cap the request is rejected 422 — contact sales. Reads echo the requested value, never null. Filling the disk gives the writing process a plain ENOSPC write error — the workload keeps running; deleting files frees space immediately. */
    ephemeralStorageBytes?: number | undefined;
}
