// This file was auto-generated by Fern from our API Definition.

export interface ResourceSpec {
    /** RAM allocation in bytes. Minimum 134217728 (128 MiB) — below that no real image starts, so sub-floor requests are rejected here instead of surfacing as a confusing in-guest OOM after boot. */
    memoryBytes: number;
    /** CPU allocation in millicores (1000 = 1 vCPU). */
    cpuMillis: number;
    /** Persistent volume size in bytes. The volume is mounted read-write at `/data` inside the workload; it survives stop/start and follows the runtime for life. Writable by the workload's own user, whatever the image runs as — root or not, no setup needed: the volume root arrives group-writable to a platform group the workload process automatically carries as a supplementary group. Files the workload creates keep their normal ownership. Software that demands strict permissions on its data directory (e.g. PostgreSQL's initdb) should use a subdirectory and set its own mode (`mkdir -m 700 /data/pgdata`). This is the only metered disk. */
    storageBytes: number;
    /** Rootfs scratch-disk budget in bytes. The rootfs is a real block disk of a fixed tier size (4 or 8 GiB); the ask rounds UP to the smallest tier that fits, and `df /` inside the workload reports that tier honestly. Ephemeral: fresh from the image on every pod recreate; durable data belongs on `/data`. Bundled, never billed. Omitted → 4 GiB default. Free up to the 8 GiB cap; above the cap the request is rejected 422 — contact sales. Reads echo the requested value, never null. Filling the disk gives the writing process a plain ENOSPC write error — the workload keeps running; deleting files frees space immediately. */
    ephemeralStorageBytes?: number | undefined;
}
