// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../index.js";

export interface Runtime {
    id: string;
    desiredState: Runtime.DesiredState;
    /** Bumped on each desired-state change. */
    generation: number;
    /** The image ref this runtime runs (echoed from create). */
    image: string;
    /** The env map, echoed in full ({} when none) — env is configuration, not a secret store. */
    env: Record<string, string>;
    /** The CMD override as set at create (Docker semantics). Absent = the image runs its own CMD — the orchestrator never inspects the image, so it cannot echo a default. */
    command?: string[] | undefined;
    /** The ENTRYPOINT override as set at create (Docker semantics). Absent = image default. */
    entrypoint?: string[] | undefined;
    resources: PlanirApi.ResourceSpec;
    /** The rootfs hardening knob as set at create (default false). */
    rootfsReadOnly: boolean;
    /** Exposed ports the client declared at create (echoed back as bare integers). */
    ports: number[];
    /** Reach handle per declared port, keyed by the port number as a string ({} when no ports are declared). The same opaque, placement-free handle POST /v1/runtimes/{id}/reach returns — the client parses nothing out of it. The handle exists from create; it serves traffic once the workload passes readiness (before that the edge answers with an error status). */
    urls: Record<string, string>;
    readiness?: PlanirApi.ReadinessSpec | undefined;
    network?: PlanirApi.NetworkSpec | undefined;
    /** Correlation labels, echoed in full ({} when none). */
    metadata: Record<string, string>;
    /** The public location this runtime runs in (e.g. "brq") — the resolved value, always present (the client's choice, or the default when omitted). The internal cluster and node are never exposed. */
    region: string;
    clientRef: string;
}

export namespace Runtime {
    export const DesiredState = {
        Running: "running",
        Stopped: "stopped",
        Destroyed: "destroyed",
    } as const;
    export type DesiredState = (typeof DesiredState)[keyof typeof DesiredState];
}
