// This file was auto-generated by Fern from our API Definition.

/**
 * The runtime is destroyed — terminal. The handle stays readable; nothing else can succeed.
 */
export interface RuntimeDestroyedError {
    error: RuntimeDestroyedError.Error_;
}

export namespace RuntimeDestroyedError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            InvalidState: "INVALID_STATE",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
