// This file was auto-generated by Fern from our API Definition.

/**
 * Runtime key rotation requires a non-destroyed runtime created with `spawn: true`.
 */
export interface RuntimeKeyUnavailableError {
    error: RuntimeKeyUnavailableError.Error_;
}

export namespace RuntimeKeyUnavailableError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            InvalidState: "INVALID_STATE",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
