// This file was auto-generated by Fern from our API Definition.

export interface TeamLedgerEntry {
    id: string;
    /** topup / bonus add to the balance (positive); usage_debit subtracts (negative); adjustment is a signed correction (either way, never zero). */
    kind: TeamLedgerEntry.Kind;
    /** Signed integer microcents — positive adds to the balance, negative subtracts. Exact for every realistic amount (orders of magnitude below 2^53). */
    amountMicrocents: number;
    /** The row's dedup handle: your own key on a topup/adjustment, or a self-describing `usage:{runtime}:{period}:{total}` on a usage debit — how you correlate a row to the write that produced it. */
    idempotencyKey: string;
    /** The Stripe event id on a webhook topup; null on every other row. */
    stripeRef: string | null;
    /** When the row was appended (ISO-8601 UTC). */
    createdAt: string;
}

export namespace TeamLedgerEntry {
    /** topup / bonus add to the balance (positive); usage_debit subtracts (negative); adjustment is a signed correction (either way, never zero). */
    export const Kind = {
        Topup: "topup",
        UsageDebit: "usage_debit",
        Adjustment: "adjustment",
        Bonus: "bonus",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
