// This file was auto-generated by Fern from our API Definition.

export interface TeamLimits {
    /** Gate B — the running-runtime count cap (the same value as `package.concurrencyLimit`; breach = 429 CONCURRENCY_LIMIT). */
    maxConcurrentRuntimes: number;
    /** Gate A — exactly these presets are creatable, regardless of billing mode; null = no explicit set (a metered team must still match SOME public preset; see GET /v1/presets). Breach = 422 INVALID_REQUEST. */
    allowedPresetIds: string[] | null;
    /** Gate C — per-family resource ceilings over RUNNING runtimes, region-blind (where each runtime lands stays your choice). A family absent here is uncapped; breach = 429 RESOURCE_QUOTA. A ceiling is an entitlement, never a capacity reservation — a create under quota can still see 503 NO_CAPACITY in a full location. */
    families: Record<string, TeamLimits.Families.Value>;
}

export namespace TeamLimits {
    export namespace Families {
        export interface Value {
            /** Ceiling on the SUM of vCPU-millis across the family's running runtimes. */
            maxVcpuMillis: number;
            /** Ceiling on the SUM of memory bytes across the family's running runtimes. */
            maxMemoryBytes: number;
        }
    }
}
