// This file was auto-generated by Fern from our API Definition.

export interface TeamUsageVolumeWindow {
    volumeId: string;
    /** The UTC calendar month this accrual covers, `YYYY-MM`. */
    period: string;
    /** Milliseconds the volume sat DETACHED in the month. Attached time never appears here — it bills through the holding runtime's window storage line. */
    detachedMs: number;
    /** What this accrual has billed so far, integer microcents — provisioned bytes × the carried rate × detached time, NO free allowance (parked capacity bills from byte zero). 0 on flat packages (quantities accrue, nothing is debited). */
    billedMicrocents: number;
    /** The accrual's own carried storage rate, copied from the package when it opened — a reprice never rewrites a month in progress. */
    storageMicrocentsPerGibMonth: number;
    /** open = still accruing this month; closed = final (volume delete or month rollover, past the event-visibility skew bound). */
    state: TeamUsageVolumeWindow.State;
    /** When the accrual closed (ISO-8601), or null while open. */
    closedAt: string | null;
}

export namespace TeamUsageVolumeWindow {
    /** open = still accruing this month; closed = final (volume delete or month rollover, past the event-visibility skew bound). */
    export const State = {
        Open: "open",
        Closed: "closed",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
