// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../index.js";

export interface Team {
    id: string;
    name: string;
    /** root = the platform operator; customer = an ordinary tenant. */
    kind: Team.Kind;
    package: PlanirApi.TeamPackageSummary;
    limits: PlanirApi.TeamLimits;
    /** The saved default location (`PATCH /v1/team`): where a create that names no `region` places, consumed exactly as if the call had sent it — an explicit per-call `region` always wins, and a default whose location stops offering the preset refuses with 422 rather than silently re-routing. Null = no default (a region-less create places cheapest-available). */
    defaultRegion: string | null;
    /** Current ledger balance in integer microcents (1 USD = 100,000,000) — the sum of every ledger row (topups and bonuses add, usage debits subtract). Metered teams must keep this above zero to create or start runtimes; flat teams (root included) ignore it. Integer over the wire (Stripe-style); exact for every realistic balance (orders of magnitude below 2^53). */
    balanceMicrocents: number;
}

export namespace Team {
    /** root = the platform operator; customer = an ordinary tenant. */
    export const Kind = {
        Root: "root",
        Customer: "customer",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
