// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../index.js";

export interface TeamUsage {
    /** The UTC calendar month these windows cover, `YYYY-MM`. */
    period: string;
    windows: PlanirApi.TeamUsageWindow[];
    /** Sums across the returned windows — this team's month total. Derived from the window rows themselves (the invoice lines); no money is re-computed on read. */
    totals: TeamUsage.Totals;
}

export namespace TeamUsage {
    /**
     * Sums across the returned windows — this team's month total. Derived from the window rows themselves (the invoice lines); no money is re-computed on read.
     */
    export interface Totals {
        billedMicrocents: number;
        meteredMs: number;
        wallMs: number;
    }
}
