// This file was auto-generated by Fern from our API Definition.

export interface Usage {
    windowStart: string;
    windowEnd: string;
    /** vCPU-seconds over running spans (string — big number). */
    cpuSeconds: string;
    memoryByteSeconds: string;
    storageByteSeconds: string;
    /** NOT YET METERED — always "0". Placeholder until per-runtime CNI egress metering lands; a biller MUST NOT treat this as a measured value. */
    egressBytes: string;
}
