// This file was auto-generated by Fern from our API Definition.

export interface Usage {
    windowStart: string;
    windowEnd: string;
    /** vCPU-seconds over confirmed allocation spans (string — big number). */
    cpuSeconds: string;
    memoryByteSeconds: string;
    storageByteSeconds: string;
    /** Counter, not money: compressed runtime-layer bytes recorded for committed rootfs images integrated over billable presence. Excludes allocated rootfs tiers, shared base-image layers, volume capacity, and storage-system overhead. */
    preservedRootfsByteSeconds: string;
    /** NOT YET METERED — always "0". Placeholder until per-runtime egress metering lands; a biller MUST NOT treat this as a measured value. */
    egressBytes: string;
}
