// This file was auto-generated by Fern from our API Definition.

/**
 * The volume is attached (or mid-delete): attachment spans the holding runtime's whole life — stop does not release it. Destroy the runtime first; no force-detach exists in v1.
 */
export interface VolumeBusyError {
    error: VolumeBusyError.Error_;
}

export namespace VolumeBusyError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            VolumeBusy: "VOLUME_BUSY",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
