// This file was auto-generated by Fern from our API Definition.

/**
 * No such volume for this team (unknown, malformed, or another team's id — never disclosed which).
 */
export interface VolumeNotFoundError {
    error: VolumeNotFoundError.Error_;
}

export namespace VolumeNotFoundError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            NotFound: "NOT_FOUND",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
