// This file was auto-generated by Fern from our API Definition.

/**
 * A volume with this name already exists in the team — names are unique per team.
 */
export interface VolumeNameConflictError {
    error: VolumeNameConflictError.Error_;
}

export namespace VolumeNameConflictError {
    export interface Error_ {
        code: Error_.Code;
        message?: string | undefined;
    }

    export namespace Error_ {
        export const Code = {
            Conflict: "CONFLICT",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
