// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../index.js";

export interface WebhookDeliveriesList {
    deliveries: PlanirApi.WebhookDelivery[];
}
