// This file was auto-generated by Fern from our API Definition.

/** A lifecycle event type, dot-namespaced. `created` = the runtime record exists; `running` = observed running; `error` = observed in error (fires per transition — deduplicate by event id); `destroyed` = observed destroyed (terminal). Unknown types in a filter are refused at registration. */
export const WebhookEventType = {
    RuntimeLifecycleCreated: "runtime.lifecycle.created",
    RuntimeLifecycleRunning: "runtime.lifecycle.running",
    RuntimeLifecycleError: "runtime.lifecycle.error",
    RuntimeLifecycleDestroyed: "runtime.lifecycle.destroyed",
    RuntimeLifecycleStopped: "runtime.lifecycle.stopped",
    RuntimeLifecycleStopFailed: "runtime.lifecycle.stop_failed",
} as const;
export type WebhookEventType = (typeof WebhookEventType)[keyof typeof WebhookEventType];
