// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../index.js";

export interface WebhookDelivery {
    /** The delivery row id — the handle for redelivery. */
    id: string;
    /** The wire event id (`evt_<n>`, monotonic) — equals the delivery's `webhook-id` header and payload `id`, INCLUDING across retries and manual redelivery: deduplicate by this. */
    eventId: string;
    eventType: PlanirApi.WebhookEventType;
    /** The runtime the event concerns. */
    runtimeId: string;
    /** When the event occurred — the payload `timestamp`. */
    occurredAt: string;
    /** `pending` = scheduled (first attempt or mid-retry); `succeeded` = a 2xx landed; `exhausted` = every scheduled attempt failed (redeliver to retry manually). */
    state: WebhookDelivery.State;
    /** Attempts made so far. */
    attempts: number;
    /** The next scheduled attempt while `pending`; null once settled. */
    nextAttemptAt: string | null;
    /** HTTP status of the last attempt; null before any attempt or on a non-HTTP failure. */
    lastStatus: number | null;
    /** Failure class of the last failed attempt (`http_<status>`, `timeout`, `network`, `dns`, `ssrf_denied`); null before any attempt and after a success. */
    lastError: string | null;
    /** Wall-clock of the last attempt. */
    lastDurationMs: number | null;
    createdAt: string;
}

export namespace WebhookDelivery {
    /** `pending` = scheduled (first attempt or mid-retry); `succeeded` = a 2xx landed; `exhausted` = every scheduled attempt failed (redeliver to retry manually). */
    export const State = {
        Pending: "pending",
        Succeeded: "succeeded",
        Exhausted: "exhausted",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
