# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.presets_list import PresetsList
from .raw_client import AsyncRawPresetsClient, RawPresetsClient


class PresetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPresetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPresetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPresetsClient
        """
        return self._raw_client

    def list_presets(self, *, request_options: typing.Optional[RequestOptions] = None) -> PresetsList:
        """
        Every publicly available preset, plus any private presets negotiated for the caller's own plan. Ordered public-first, then family, then cpu. Prices are integer microcents (1 USD = 100,000,000); a repriced preset never changes a billing month already in progress.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PresetsList
            The catalog.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.presets.list_presets()
        """
        _response = self._raw_client.list_presets(request_options=request_options)
        return _response.data


class AsyncPresetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPresetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPresetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPresetsClient
        """
        return self._raw_client

    async def list_presets(self, *, request_options: typing.Optional[RequestOptions] = None) -> PresetsList:
        """
        Every publicly available preset, plus any private presets negotiated for the caller's own plan. Ordered public-first, then family, then cpu. Prices are integer microcents (1 USD = 100,000,000); a repriced preset never changes a billing month already in progress.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PresetsList
            The catalog.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.presets.list_presets()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_presets(request_options=request_options)
        return _response.data
