# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_version_info import ApiVersionInfo
    from .api_version_info_version import ApiVersionInfoVersion
    from .detached_exec import DetachedExec
    from .detached_exec_status import DetachedExecStatus
    from .error import Error
    from .error_error import ErrorError
    from .error_error_code import ErrorErrorCode
    from .event import Event
    from .events_list import EventsList
    from .exec_id import ExecId
    from .exec_request import ExecRequest
    from .exec_result import ExecResult
    from .health_status import HealthStatus
    from .health_status_status import HealthStatusStatus
    from .network_spec import NetworkSpec
    from .observed import Observed
    from .observed_last_exit import ObservedLastExit
    from .observed_phase import ObservedPhase
    from .reach import Reach
    from .readiness_spec import ReadinessSpec
    from .resource_spec import ResourceSpec
    from .runtime import Runtime
    from .runtime_desired_state import RuntimeDesiredState
    from .runtime_with_observed import RuntimeWithObserved
    from .runtimes_list import RuntimesList
    from .usage import Usage
    from .usage_list import UsageList
_dynamic_imports: typing.Dict[str, str] = {
    "ApiVersionInfo": ".api_version_info",
    "ApiVersionInfoVersion": ".api_version_info_version",
    "DetachedExec": ".detached_exec",
    "DetachedExecStatus": ".detached_exec_status",
    "Error": ".error",
    "ErrorError": ".error_error",
    "ErrorErrorCode": ".error_error_code",
    "Event": ".event",
    "EventsList": ".events_list",
    "ExecId": ".exec_id",
    "ExecRequest": ".exec_request",
    "ExecResult": ".exec_result",
    "HealthStatus": ".health_status",
    "HealthStatusStatus": ".health_status_status",
    "NetworkSpec": ".network_spec",
    "Observed": ".observed",
    "ObservedLastExit": ".observed_last_exit",
    "ObservedPhase": ".observed_phase",
    "Reach": ".reach",
    "ReadinessSpec": ".readiness_spec",
    "ResourceSpec": ".resource_spec",
    "Runtime": ".runtime",
    "RuntimeDesiredState": ".runtime_desired_state",
    "RuntimeWithObserved": ".runtime_with_observed",
    "RuntimesList": ".runtimes_list",
    "Usage": ".usage",
    "UsageList": ".usage_list",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiVersionInfo",
    "ApiVersionInfoVersion",
    "DetachedExec",
    "DetachedExecStatus",
    "Error",
    "ErrorError",
    "ErrorErrorCode",
    "Event",
    "EventsList",
    "ExecId",
    "ExecRequest",
    "ExecResult",
    "HealthStatus",
    "HealthStatusStatus",
    "NetworkSpec",
    "Observed",
    "ObservedLastExit",
    "ObservedPhase",
    "Reach",
    "ReadinessSpec",
    "ResourceSpec",
    "Runtime",
    "RuntimeDesiredState",
    "RuntimeWithObserved",
    "RuntimesList",
    "Usage",
    "UsageList",
]
