# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .api_version_info_version import ApiVersionInfoVersion


class ApiVersionInfo(UniversalBaseModel):
    version: ApiVersionInfoVersion

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
