# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .api_key import ApiKey


class ApiKeyMint(ApiKey):
    secret: str = pydantic.Field()
    """
    The plaintext API key — returned exactly once, at mint, and never retrievable again. Send it as `Authorization: Bearer <secret>`. Store it securely now; the server keeps only a one-way digest.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
