# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class ApiKey(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Stable key id — the handle for `DELETE /v1/team/keys/{id}`.
    """

    prefix_hint: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="prefixHint"),
        pydantic.Field(
            alias="prefixHint",
            description="Display prefix: `plnr_` + the first 4 random characters (e.g. `plnr_ab12`) — enough to recognise a key in a list, never enough to use it.",
        ),
    ]
    last4: str = pydantic.Field()
    """
    The key’s last 4 characters, to disambiguate keys that share a prefix.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The optional display name set at mint; null when unnamed.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the key was minted (ISO-8601 UTC)."),
    ]
    last_used_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastUsedAt"),
        pydantic.Field(
            alias="lastUsedAt",
            default=None,
            description="Approximate time of the key’s most recent authenticated request (best-effort, throttled to ≤ 1 update/minute); null until first used.",
        ),
    ]
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt",
            default=None,
            description="When the key expires, if an expiry was set at mint; null = never expires (the machine-credential norm). An expired key fails authentication exactly like a revoked one.",
        ),
    ]
    revoked_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="revokedAt"),
        pydantic.Field(
            alias="revokedAt",
            default=None,
            description="When the key was revoked; null = active. A revoked key is preserved for audit and fails authentication on its next request.",
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
