# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .billing_not_ready_error_error import BillingNotReadyErrorError


class BillingNotReadyError(UniversalBaseModel):
    """
    Metered billing catch-up is incomplete. Nothing is provisioned or charged; retry later.
    """

    error: BillingNotReadyErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
