# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .detached_exec_status import DetachedExecStatus


class DetachedExec(UniversalBaseModel):
    status: DetachedExecStatus = pydantic.Field()
    """
    running = still executing; exited = final, stop polling.
    """

    exit_code: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="exitCode"),
        pydantic.Field(
            alias="exitCode",
            default=None,
            description="Null while running. After exit: the process exit code, or null when the outcome is unknown (stream cut, or the 30-minute detached ceiling hit — stderr says which in stable words). The ceiling stops output CAPTURE, not the process: it may still be running in the runtime; kill it via exec if that matters.",
        ),
    ]
    stdout: str = pydantic.Field()
    """
    Captured stdout SO FAR (final once exited), truncated at 1 MiB with a marker.
    """

    stderr: str = pydantic.Field()
    """
    Captured stderr SO FAR (final once exited), truncated at 1 MiB with a marker.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
