# This file was auto-generated by Fern from our API Definition.

import typing

ErrorErrorCode = typing.Union[
    typing.Literal[
        "UNAUTHENTICATED",
        "INVALID_REQUEST",
        "NOT_FOUND",
        "INVALID_STATE",
        "CONFLICT",
        "RATE_LIMITED",
        "CONCURRENCY_LIMIT",
        "INSUFFICIENT_BALANCE",
        "VOLUME_BUSY",
        "TEAM_BLOCKED",
        "FORBIDDEN",
        "INTERNAL",
    ],
    typing.Any,
]
