# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class ExecId(UniversalBaseModel):
    exec_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="execId"),
        pydantic.Field(
            alias="execId",
            description="Handle for polling GET /v1/runtimes/{id}/exec/{execId}. Scoped to its runtime; results are retained briefly post-exit, then the id 404s.",
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
