# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .exec_list_execs_item_status import ExecListExecsItemStatus


class ExecListExecsItem(UniversalBaseModel):
    exec_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="execId"),
        pydantic.Field(alias="execId", description="Poll handle — GET /v1/runtimes/{id}/exec/{execId}."),
    ]
    status: ExecListExecsItemStatus = pydantic.Field()
    """
    running = still executing; exited = final (briefly retained).
    """

    command: typing.List[str] = pydantic.Field()
    """
    The exact argv this exec was started with (echoed).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
