# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .invalid_request_error_error import InvalidRequestErrorError


class InvalidRequestError(UniversalBaseModel):
    """
    Shape validation refused the request: bad JSON, a malformed field, or a violated bound.
    """

    error: InvalidRequestErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
