# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .no_capacity_error_error import NoCapacityErrorError


class NoCapacityError(UniversalBaseModel):
    """
    The requested location cannot take this resource right now — it is full, draining, or not yet live. Nothing is provisioned and nothing is charged; retry later or pick another region (GET /v1/regions). Never a silent cross-location fallback.
    """

    error: NoCapacityErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
