# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .observed_entrypoint_zero_state import ObservedEntrypointZeroState


class ObservedEntrypointZero(UniversalBaseModel):
    state: ObservedEntrypointZeroState
    exit_code: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="exitCode"), pydantic.Field(alias="exitCode", default=None)
    ]
    at: typing.Optional[typing.Any] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
