# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .payment_rail_unavailable_error_error_code import PaymentRailUnavailableErrorErrorCode


class PaymentRailUnavailableErrorError(UniversalBaseModel):
    code: PaymentRailUnavailableErrorErrorCode
    message: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
