# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .policy_refused_error_error import PolicyRefusedErrorError


class PolicyRefusedError(UniversalBaseModel):
    """
    A policy gate (not shape validation) refused a well-formed request; the message names the gate.
    """

    error: PolicyRefusedErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
