# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .rate_limited_error_error import RateLimitedErrorError


class RateLimitedError(UniversalBaseModel):
    """
    The per-key request-rate budget is exhausted; wait `Retry-After` seconds and retry.
    """

    error: RateLimitedErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
