# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class Reach(UniversalBaseModel):
    url: str = pydantic.Field()
    """
    Opaque, placement-free reach handle (e.g. https://<port>--<id>.<base>). The client parses nothing out of it; the shape is not a wire contract.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
