# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .registry_host_exists_error_error import RegistryHostExistsErrorError


class RegistryHostExistsError(UniversalBaseModel):
    """
    The team already holds a credential for this registry host — at most one per host (matching stays deterministic). Rotate or delete the existing credential instead.
    """

    error: RegistryHostExistsErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
