# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .registry_credential_not_found_error_error_code import RegistryCredentialNotFoundErrorErrorCode


class RegistryCredentialNotFoundErrorError(UniversalBaseModel):
    code: RegistryCredentialNotFoundErrorErrorCode
    message: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
