# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .region_family_availability import RegionFamilyAvailability


class Region(UniversalBaseModel):
    region: str = pydantic.Field()
    """
    The public location label (e.g. "brq") — a plain string, never an enum; new locations appear additively. The value create requests accept as `region`.
    """

    families: typing.List[RegionFamilyAvailability] = pydantic.Field()
    """
    Per-family availability at this location, family-ASC. A catalogued-but-full family stays LISTED with `available: false`; an EMPTY array means no family is catalogued here at all (the label listed so it is discoverable ahead of commissioning) — two different facts.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
