# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .region import Region


class RegionsList(UniversalBaseModel):
    regions: typing.List[Region] = pydantic.Field()
    """
    Every catalogued location, region-ASC.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
