# This file was auto-generated by Fern from our API Definition.

import typing

RuntimeCreatePolicyErrorErrorCode = typing.Union[
    typing.Literal["INVALID_REQUEST", "UNSAFE_IMAGE_HOST", "UNSUPPORTED_IMAGE_PLATFORM", "INVALID_IMAGE_CONFIG"],
    typing.Any,
]
