# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .runtime_timeout_desired_state import RuntimeTimeoutDesiredState
from .runtime_timeout_on_timeout import RuntimeTimeoutOnTimeout


class RuntimeTimeout(UniversalBaseModel):
    desired_state: typing_extensions.Annotated[
        RuntimeTimeoutDesiredState, FieldMetadata(alias="desiredState"), pydantic.Field(alias="desiredState")
    ]
    timeout: int
    on_timeout: typing_extensions.Annotated[
        RuntimeTimeoutOnTimeout, FieldMetadata(alias="onTimeout"), pydantic.Field(alias="onTimeout")
    ]
    timeout_at: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="timeoutAt"), pydantic.Field(alias="timeoutAt", default=None)
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
