# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .runtime_key_unavailable_error_error_code import RuntimeKeyUnavailableErrorErrorCode


class RuntimeKeyUnavailableErrorError(UniversalBaseModel):
    code: RuntimeKeyUnavailableErrorErrorCode
    message: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
