# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .team_blocked_error_error import TeamBlockedErrorError


class TeamBlockedError(UniversalBaseModel):
    """
    The team is blocked: writes and non-billing reads are refused until support unblocks it.
    """

    error: TeamBlockedErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
