# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .team_kind import TeamKind
from .team_package_summary import TeamPackageSummary


class Team(UniversalBaseModel):
    id: str
    name: str
    kind: TeamKind = pydantic.Field()
    """
    root = the platform operator; customer = an ordinary tenant.
    """

    package: TeamPackageSummary
    balance_microcents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="balanceMicrocents"),
        pydantic.Field(
            alias="balanceMicrocents",
            description="Current ledger balance in integer microcents (1 USD = 100,000,000) — the sum of every ledger row (topups and bonuses add, usage debits subtract). Metered teams must keep this above zero to create or start runtimes; flat teams (root included) ignore it. Integer over the wire (Stripe-style); exact for every realistic balance (orders of magnitude below 2^53).",
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
