# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .team_usage_volume_window_state import TeamUsageVolumeWindowState


class TeamUsageVolumeWindow(UniversalBaseModel):
    volume_id: typing_extensions.Annotated[str, FieldMetadata(alias="volumeId"), pydantic.Field(alias="volumeId")]
    period: str = pydantic.Field()
    """
    The UTC calendar month this accrual covers, `YYYY-MM`.
    """

    detached_ms: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="detachedMs"),
        pydantic.Field(
            alias="detachedMs",
            description="Milliseconds the volume sat DETACHED in the month. Attached time never appears here — it bills through the holding runtime's window storage line.",
        ),
    ]
    billed_microcents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="billedMicrocents"),
        pydantic.Field(
            alias="billedMicrocents",
            description="What this accrual has billed so far, integer microcents — provisioned bytes × the carried rate × detached time, NO free allowance (parked capacity bills from byte zero). 0 on flat packages (quantities accrue, nothing is debited).",
        ),
    ]
    storage_microcents_per_gib_month: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="storageMicrocentsPerGibMonth"),
        pydantic.Field(
            alias="storageMicrocentsPerGibMonth",
            description="The accrual's own carried storage rate, copied from the package when it opened — a reprice never rewrites a month in progress.",
        ),
    ]
    state: TeamUsageVolumeWindowState = pydantic.Field()
    """
    open = still accruing this month; closed = final (volume delete or month rollover, past the event-visibility skew bound).
    """

    closed_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="closedAt"),
        pydantic.Field(
            alias="closedAt", default=None, description="When the accrual closed (ISO-8601), or null while open."
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
