# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .volume_not_found_error_error import VolumeNotFoundErrorError


class VolumeNotFoundError(UniversalBaseModel):
    """
    No such volume for this team (unknown, malformed, or another team's id — never disclosed which).
    """

    error: VolumeNotFoundErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
