# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .volume_name_conflict_error_error import VolumeNameConflictErrorError


class VolumeNameConflictError(UniversalBaseModel):
    """
    A volume with this name already exists in the team — names are unique per team.
    """

    error: VolumeNameConflictErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
