# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .volume_busy_error_error import VolumeBusyErrorError


class VolumeBusyError(UniversalBaseModel):
    """
    The volume is attached (or mid-delete): attachment spans the holding runtime's whole life — stop does not release it. Destroy the runtime first; no force-detach exists in v1.
    """

    error: VolumeBusyErrorError

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
