# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .volume_busy_error_error_code import VolumeBusyErrorErrorCode


class VolumeBusyErrorError(UniversalBaseModel):
    code: VolumeBusyErrorErrorCode
    message: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
