# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_event_envelope_version import WebhookEventEnvelopeVersion
from .webhook_event_type import WebhookEventType


class WebhookEventEnvelope(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The event id (`evt_<n>`, monotonic) — identical to the `webhook-id` header, and STABLE across retries and manual redelivery: deduplicate by it.
    """

    version: WebhookEventEnvelopeVersion = pydantic.Field()
    """
    Envelope version. New event types arrive additively and never change it.
    """

    type: WebhookEventType
    timestamp: dt.datetime = pydantic.Field()
    """
    When the event occurred (not when this delivery was attempted).
    """

    team_id: str = pydantic.Field()
    """
    The team the runtime belongs to.
    """

    runtime_id: str = pydantic.Field()
    """
    The runtime the event concerns.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
