# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_delivery_not_found_error_error_code import WebhookDeliveryNotFoundErrorErrorCode


class WebhookDeliveryNotFoundErrorError(UniversalBaseModel):
    code: WebhookDeliveryNotFoundErrorErrorCode
    message: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
