# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_event_type import WebhookEventType


class WebhookEndpoint(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Stable endpoint id — the handle for the endpoint routes.
    """

    url: str = pydantic.Field()
    """
    The receiver URL.
    """

    event_types: typing_extensions.Annotated[
        typing.Optional[typing.List[WebhookEventType]],
        FieldMetadata(alias="eventTypes"),
        pydantic.Field(
            alias="eventTypes", default=None, description="The event-type filter; absent = all lifecycle types."
        ),
    ]
    enabled: bool = pydantic.Field()
    """
    false = deliveries are stopped (auto-disabled after sustained failure, per the delivery policy). Re-enable explicitly via POST …/{id}/enable; pending deliveries resume.
    """

    prefix_hint: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="prefixHint"),
        pydantic.Field(
            alias="prefixHint",
            description="Display prefix of the signing secret: `whsec_` + the first 4 characters — enough to recognise it, never enough to verify with.",
        ),
    ]
    failing_since: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="failingSince"),
        pydantic.Field(
            alias="failingSince",
            default=None,
            description="Set while the endpoint is on the auto-disable clock: the instant its current failure streak began (a delivery exhausted its retry schedule). Null = healthy (any successful delivery clears it). When it grows older than the disable window, the endpoint flips to `enabled: false`.",
        ),
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
