# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key import ApiKey
from ..types.api_key_list import ApiKeyList
from ..types.api_key_mint import ApiKeyMint
from ..types.team import Team
from ..types.team_ledger import TeamLedger
from ..types.team_usage import TeamUsage
from ..types.topup import Topup
from .raw_client import AsyncRawTeamClient, RawTeamClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TeamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTeamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTeamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTeamClient
        """
        return self._raw_client

    def get_team(self, *, request_options: typing.Optional[RequestOptions] = None) -> Team:
        """
        The team the credential belongs to — its identity, package summary, and current ledger balance. No path parameter: a caller can only ever read its own team.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Team
            The caller's team.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.get_team()
        """
        _response = self._raw_client.get_team(request_options=request_options)
        return _response.data

    def get_team_usage(
        self, *, period: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> TeamUsage:
        """
        Every billing window for the caller's team in one UTC calendar month (`?period=YYYY-MM`, default the current month), plus the month totals. Each window is an invoice line: the accrued quantities and the prices it carries. A malformed period is 400.

        Parameters
        ----------
        period : typing.Optional[str]
            UTC calendar month `YYYY-MM`. Omitted = the current UTC month.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TeamUsage
            The month's windows and totals.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.get_team_usage()
        """
        _response = self._raw_client.get_team_usage(period=period, request_options=request_options)
        return _response.data

    def get_team_ledger(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TeamLedger:
        """
        The append-only money log for the caller's team, newest first. Pages via `?limit=` (1–100, default 20) + `?cursor=` (opaque; pass the previous page's `nextCursor` verbatim). Each row is signed integer microcents; the balance is their sum.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, 1–100 (default 20).

        cursor : typing.Optional[str]
            Opaque page cursor — pass the previous page's `nextCursor` verbatim. Omitted = from the newest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TeamLedger
            One page of ledger entries, `nextCursor` present iff another page exists.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.get_team_ledger()
        """
        _response = self._raw_client.get_team_ledger(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def list_team_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKeyList:
        """
        Every API key the caller's team holds, newest first — active and revoked — as display metadata only (prefix hint, last 4, name, timestamps). Never the plaintext, never the digest.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyList
            The team's keys.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.list_team_keys()
        """
        _response = self._raw_client.list_team_keys(request_options=request_options)
        return _response.data

    def mint_team_key(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyMint:
        """
        Creates a new API key for the caller's own team and returns its plaintext exactly once (the `secret` field). The plaintext is never stored, logged, or retrievable again — the server keeps only a one-way digest. A key may mint sibling keys (same privilege level). Refused with 422 when the team already holds its maximum of active keys; revoke one to free a slot.

        Parameters
        ----------
        name : typing.Optional[str]
            Optional display name to recognise the key later (1–200 chars).

        expires_at : typing.Optional[dt.datetime]
            Optional ISO-8601 expiry (GitHub-style hygiene, on request). Omitted = never expires — the machine-credential norm; expiry is never forced (scheduled key death breaks live integrations).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyMint
            The minted key — `secret` carries the plaintext, shown this once only.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.mint_team_key()
        """
        _response = self._raw_client.mint_team_key(name=name, expires_at=expires_at, request_options=request_options)
        return _response.data

    def revoke_team_key(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKey:
        """
        Soft-revokes the key (sets `revokedAt`; the row is kept for audit) and returns its updated metadata. The revoked key fails authentication on its next request. Revoking the very credential making the request is allowed — the caller locks itself out while the team's other keys keep working. A key id that is unknown or belongs to another team is a 404, indistinguishable either way.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKey
            The revoked key's updated metadata.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.revoke_team_key(
            id="id",
        )
        """
        _response = self._raw_client.revoke_team_key(id, request_options=request_options)
        return _response.data

    def create_team_topup(
        self,
        *,
        amount_microcents: int,
        success_url: str,
        cancel_url: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Topup:
        """
        Creates a Stripe Checkout Session to add prepaid credit to the caller's own team balance and returns the hosted payment URL (`checkoutUrl`) to redirect the payer to. The balance is credited only after Stripe confirms the payment (server-to-server webhook), with the amount Stripe actually charged. Amount is USD integer microcents — a whole number of cents between $1 and $100,000. Responds 503 when the Stripe payment rail is not configured on this deployment.

        Parameters
        ----------
        amount_microcents : int
            Credit to add, in USD integer microcents (1 USD = 100,000,000). A whole number of US cents (a multiple of 1,000,000), between $1 (100,000,000) and $100,000 (10,000,000,000,000). The balance is credited with what Stripe actually charges, not this requested value.

        success_url : str
            Absolute URL Stripe returns the payer to after a completed payment.

        cancel_url : str
            Absolute URL Stripe returns the payer to if they abandon the payment.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Topup
            The Checkout Session was created; redirect the payer to `checkoutUrl`.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.team.create_team_topup(
            amount_microcents=1,
            success_url="successUrl",
            cancel_url="cancelUrl",
        )
        """
        _response = self._raw_client.create_team_topup(
            amount_microcents=amount_microcents,
            success_url=success_url,
            cancel_url=cancel_url,
            request_options=request_options,
        )
        return _response.data


class AsyncTeamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTeamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTeamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTeamClient
        """
        return self._raw_client

    async def get_team(self, *, request_options: typing.Optional[RequestOptions] = None) -> Team:
        """
        The team the credential belongs to — its identity, package summary, and current ledger balance. No path parameter: a caller can only ever read its own team.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Team
            The caller's team.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.get_team()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_team(request_options=request_options)
        return _response.data

    async def get_team_usage(
        self, *, period: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> TeamUsage:
        """
        Every billing window for the caller's team in one UTC calendar month (`?period=YYYY-MM`, default the current month), plus the month totals. Each window is an invoice line: the accrued quantities and the prices it carries. A malformed period is 400.

        Parameters
        ----------
        period : typing.Optional[str]
            UTC calendar month `YYYY-MM`. Omitted = the current UTC month.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TeamUsage
            The month's windows and totals.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.get_team_usage()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_team_usage(period=period, request_options=request_options)
        return _response.data

    async def get_team_ledger(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TeamLedger:
        """
        The append-only money log for the caller's team, newest first. Pages via `?limit=` (1–100, default 20) + `?cursor=` (opaque; pass the previous page's `nextCursor` verbatim). Each row is signed integer microcents; the balance is their sum.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size, 1–100 (default 20).

        cursor : typing.Optional[str]
            Opaque page cursor — pass the previous page's `nextCursor` verbatim. Omitted = from the newest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TeamLedger
            One page of ledger entries, `nextCursor` present iff another page exists.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.get_team_ledger()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_team_ledger(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    async def list_team_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKeyList:
        """
        Every API key the caller's team holds, newest first — active and revoked — as display metadata only (prefix hint, last 4, name, timestamps). Never the plaintext, never the digest.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyList
            The team's keys.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.list_team_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_team_keys(request_options=request_options)
        return _response.data

    async def mint_team_key(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiKeyMint:
        """
        Creates a new API key for the caller's own team and returns its plaintext exactly once (the `secret` field). The plaintext is never stored, logged, or retrievable again — the server keeps only a one-way digest. A key may mint sibling keys (same privilege level). Refused with 422 when the team already holds its maximum of active keys; revoke one to free a slot.

        Parameters
        ----------
        name : typing.Optional[str]
            Optional display name to recognise the key later (1–200 chars).

        expires_at : typing.Optional[dt.datetime]
            Optional ISO-8601 expiry (GitHub-style hygiene, on request). Omitted = never expires — the machine-credential norm; expiry is never forced (scheduled key death breaks live integrations).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyMint
            The minted key — `secret` carries the plaintext, shown this once only.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.mint_team_key()


        asyncio.run(main())
        """
        _response = await self._raw_client.mint_team_key(
            name=name, expires_at=expires_at, request_options=request_options
        )
        return _response.data

    async def revoke_team_key(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ApiKey:
        """
        Soft-revokes the key (sets `revokedAt`; the row is kept for audit) and returns its updated metadata. The revoked key fails authentication on its next request. Revoking the very credential making the request is allowed — the caller locks itself out while the team's other keys keep working. A key id that is unknown or belongs to another team is a 404, indistinguishable either way.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKey
            The revoked key's updated metadata.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.revoke_team_key(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_team_key(id, request_options=request_options)
        return _response.data

    async def create_team_topup(
        self,
        *,
        amount_microcents: int,
        success_url: str,
        cancel_url: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Topup:
        """
        Creates a Stripe Checkout Session to add prepaid credit to the caller's own team balance and returns the hosted payment URL (`checkoutUrl`) to redirect the payer to. The balance is credited only after Stripe confirms the payment (server-to-server webhook), with the amount Stripe actually charged. Amount is USD integer microcents — a whole number of cents between $1 and $100,000. Responds 503 when the Stripe payment rail is not configured on this deployment.

        Parameters
        ----------
        amount_microcents : int
            Credit to add, in USD integer microcents (1 USD = 100,000,000). A whole number of US cents (a multiple of 1,000,000), between $1 (100,000,000) and $100,000 (10,000,000,000,000). The balance is credited with what Stripe actually charges, not this requested value.

        success_url : str
            Absolute URL Stripe returns the payer to after a completed payment.

        cancel_url : str
            Absolute URL Stripe returns the payer to if they abandon the payment.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Topup
            The Checkout Session was created; redirect the payer to `checkoutUrl`.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.team.create_team_topup(
                amount_microcents=1,
                success_url="successUrl",
                cancel_url="cancelUrl",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_team_topup(
            amount_microcents=amount_microcents,
            success_url=success_url,
            cancel_url=cancel_url,
            request_options=request_options,
        )
        return _response.data
