// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as PlanirApi from "../../../index.js";
import { RuntimeHandle } from "../../../../process/RuntimeHandle.js";

export declare namespace RuntimesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Runtime lifecycle, config, reach, logs, usage, events.
 */
export class RuntimesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RuntimesClient.Options>;

    constructor(options: RuntimesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public runtime(id: string): RuntimeHandle {
        return new RuntimeHandle(this._options, id);
    }

    /**
     * Pages in creation order via `?limit=` (1–100, default 20) + `?cursor=` (opaque; pass the previous page's `nextCursor` verbatim). Equality-filter on correlation labels with DYNAMIC query params of the form `?metadata.<key>=<value>` (multiple filters AND together), and on the home location with `?region=` (the `region` each response echoes). Destroyed runtimes are excluded unless `?includeDestroyed=true`. Returns desired-side handles only — read an individual runtime for its observed state.
     *
     * @param {PlanirApi.ListRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.list()
     */
    public async list(
        request: PlanirApi.ListRuntimesRequest = {},
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.Page<PlanirApi.Runtime, PlanirApi.RuntimesList>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: PlanirApi.ListRuntimesRequest): Promise<core.WithRawResponse<PlanirApi.RuntimesList>> => {
                const { limit, cursor, includeDestroyed, desiredState, region } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    includeDestroyed: includeDestroyed != null ? includeDestroyed : undefined,
                    desiredState: Array.isArray(desiredState)
                        ? desiredState.map((item) => item)
                        : desiredState != null
                          ? desiredState
                          : undefined,
                    region,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.PlanirApiEnvironment.Default,
                        "v1/runtimes",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as PlanirApi.RuntimesList, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new PlanirApi.BadRequestError(
                                _response.error.body as PlanirApi.InvalidRequestError,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new PlanirApi.UnauthorizedError(
                                _response.error.body as PlanirApi.UnauthenticatedError,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new PlanirApi.ForbiddenError(
                                _response.error.body as PlanirApi.TeamBlockedError,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new PlanirApi.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.PlanirApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/runtimes");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<PlanirApi.Runtime, PlanirApi.RuntimesList>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.nextCursor != null &&
                !(typeof response?.nextCursor === "string" && response?.nextCursor === ""),
            getItems: (response) => response?.runtimes ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * @param {PlanirApi.CreateRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.PaymentRequiredError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.UnprocessableEntityError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     * @throws {@link PlanirApi.ServiceUnavailableError}
     *
     * @example
     *     await client.runtimes.create({
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public create(
        request: PlanirApi.CreateRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.RuntimeWithObserved> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: PlanirApi.CreateRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.RuntimeWithObserved>> {
        const { "idempotency-key": idempotencyKey, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "idempotency-key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                "v1/runtimes",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.RuntimeWithObserved, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 402:
                    throw new PlanirApi.PaymentRequiredError(
                        _response.error.body as PlanirApi.InsufficientBalanceError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new PlanirApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new PlanirApi.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes");
    }

    /**
     * @param {PlanirApi.GetRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.get({
     *         id: "id"
     *     })
     */
    public get(
        request: PlanirApi.GetRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.RuntimeWithObserved> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: PlanirApi.GetRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.RuntimeWithObserved>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.RuntimeWithObserved, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/runtimes/{id}");
    }

    /**
     * @param {PlanirApi.DestroyRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.destroy({
     *         id: "id"
     *     })
     */
    public destroy(
        request: PlanirApi.DestroyRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__destroy(request, requestOptions));
    }

    private async __destroy(
        request: PlanirApi.DestroyRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/runtimes/{id}");
    }

    /**
     * Every positive success reanchors the deadline from the post-lock instant; retrying a positive request moves the deadline.
     *
     * @param {PlanirApi.SetRuntimeTimeoutBody} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.setRuntimeTimeout({
     *         id: "id",
     *         body: {
     *             timeout: 1
     *         }
     *     })
     */
    public setRuntimeTimeout(
        request: PlanirApi.SetRuntimeTimeoutBody,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__setRuntimeTimeout(request, requestOptions));
    }

    private async __setRuntimeTimeout(
        request: PlanirApi.SetRuntimeTimeoutBody,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/timeout`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes/{id}/timeout");
    }

    /**
     * Boots the newest durable committed rootfs, else the original image — a fresh process, not a resume: a runtime parked a long time wakes with expired tokens and dead TLS sessions, exactly as a rebooted machine would. Warm where it last ran, colder elsewhere (the latency class).
     *
     * @param {PlanirApi.StartRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.PaymentRequiredError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     * @throws {@link PlanirApi.ServiceUnavailableError}
     *
     * @example
     *     await client.runtimes.start({
     *         id: "id"
     *     })
     */
    public start(
        request: PlanirApi.StartRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__start(request, requestOptions));
    }

    private async __start(
        request: PlanirApi.StartRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/start`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 402:
                    throw new PlanirApi.PaymentRequiredError(
                        _response.error.body as PlanirApi.InsufficientBalanceError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new PlanirApi.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes/{id}/start");
    }

    /**
     * Ends the process: in-memory state, open connections, and sessions are gone — `start` is a fresh boot, never a resume. The rootfs is preserved by default (`preserveRootfs`) and start boots it back; everything outside `/data` survives via the committed image. Quiesce is a TERM→KILL ladder — flush in-flight buffers on SIGTERM. Returns immediately; the runtime shows `stopping` until the commit is durable, then `stopped`.
     *
     * @param {PlanirApi.StopRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.stop({
     *         id: "id"
     *     })
     */
    public stop(
        request: PlanirApi.StopRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__stop(request, requestOptions));
    }

    private async __stop(
        request: PlanirApi.StopRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/stop`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes/{id}/stop");
    }

    /**
     * A bounce, never a commit: the workload is recreated with the same image selection as `start` and desired state is unchanged, so rootfs changes since the last commit are lost — `stop` is the lever that preserves them. `/data` is intact.
     *
     * @param {PlanirApi.RestartRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.restart({
     *         id: "id"
     *     })
     */
    public restart(
        request: PlanirApi.RestartRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__restart(request, requestOptions));
    }

    private async __restart(
        request: PlanirApi.RestartRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/restart`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes/{id}/restart");
    }

    /**
     * @param {PlanirApi.RotateRuntimeKeyRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.rotateRuntimeKey({
     *         id: "id"
     *     })
     */
    public rotateRuntimeKey(
        request: PlanirApi.RotateRuntimeKeyRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.ApiKey> {
        return core.HttpResponsePromise.fromPromise(this.__rotateRuntimeKey(request, requestOptions));
    }

    private async __rotateRuntimeKey(
        request: PlanirApi.RotateRuntimeKeyRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.ApiKey>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/key`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.ApiKey, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes/{id}/key");
    }

    /**
     * @param {PlanirApi.ConfigRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.updateConfig({
     *         id: "id",
     *         config: "config"
     *     })
     */
    public updateConfig(
        request: PlanirApi.ConfigRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__updateConfig(request, requestOptions));
    }

    private async __updateConfig(
        request: PlanirApi.ConfigRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/config`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/runtimes/{id}/config");
    }

    /**
     * @param {PlanirApi.EnvRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.UnprocessableEntityError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.updateEnv({
     *         id: "id",
     *         env: {
     *             "key": "value"
     *         }
     *     })
     */
    public updateEnv(
        request: PlanirApi.EnvRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__updateEnv(request, requestOptions));
    }

    private async __updateEnv(
        request: PlanirApi.EnvRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/env`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new PlanirApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/runtimes/{id}/env");
    }

    /**
     * @param {PlanirApi.NetworkRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.updateNetwork({
     *         id: "id",
     *         network: {}
     *     })
     */
    public updateNetwork(
        request: PlanirApi.NetworkRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__updateNetwork(request, requestOptions));
    }

    private async __updateNetwork(
        request: PlanirApi.NetworkRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/network`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/runtimes/{id}/network");
    }

    /**
     * @param {PlanirApi.ReachRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.reach({
     *         id: "id",
     *         port: 1
     *     })
     */
    public reach(
        request: PlanirApi.ReachRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Reach> {
        return core.HttpResponsePromise.fromPromise(this.__reach(request, requestOptions));
    }

    private async __reach(
        request: PlanirApi.ReachRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Reach>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/reach`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Reach, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/runtimes/{id}/reach");
    }

    /**
     * Whole-map replace, validated identically to create. Labels are NOT desired state: no `generation` bump, no engine interaction, no restart — the new map is visible immediately on reads and list filters. Allowed in every non-destroyed state.
     *
     * @param {PlanirApi.MetadataRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.updateRuntimeMetadata({
     *         id: "id",
     *         metadata: {
     *             "key": "value"
     *         }
     *     })
     */
    public updateRuntimeMetadata(
        request: PlanirApi.MetadataRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.Runtime> {
        return core.HttpResponsePromise.fromPromise(this.__updateRuntimeMetadata(request, requestOptions));
    }

    private async __updateRuntimeMetadata(
        request: PlanirApi.MetadataRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.Runtime>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/metadata`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.Runtime, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/runtimes/{id}/metadata");
    }

    /**
     * Server-side bounds: the last 1000 lines, capped at 1 MiB — a tail, not an archive; ship logs from inside the workload for retention. `?previous=true` reads the PRIOR container's tail after a crash — pair with `observed.lastExit` to debug a crash loop.
     *
     * @param {PlanirApi.GetLogsRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.ConflictError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.getLogs({
     *         id: "id"
     *     })
     */
    public getLogs(
        request: PlanirApi.GetLogsRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__getLogs(request, requestOptions));
    }

    private async __getLogs(
        request: PlanirApi.GetLogsRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const { id, previous } = request;
        const _queryParams: Record<string, unknown> = {
            previous: previous != null ? previous : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/logs`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new PlanirApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/runtimes/{id}/logs");
    }

    /**
     * @param {PlanirApi.GetUsageRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.getUsage({
     *         id: "id"
     *     })
     */
    public getUsage(
        request: PlanirApi.GetUsageRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.UsageList> {
        return core.HttpResponsePromise.fromPromise(this.__getUsage(request, requestOptions));
    }

    private async __getUsage(
        request: PlanirApi.GetUsageRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.UsageList>> {
        const { id, from: from_, to } = request;
        const _queryParams: Record<string, unknown> = {
            from: from_ != null ? from_ : undefined,
            to: to != null ? to : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/usage`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.UsageList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/runtimes/{id}/usage");
    }

    /**
     * @param {PlanirApi.GetEventsRuntimesRequest} request
     * @param {RuntimesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlanirApi.BadRequestError}
     * @throws {@link PlanirApi.UnauthorizedError}
     * @throws {@link PlanirApi.ForbiddenError}
     * @throws {@link PlanirApi.NotFoundError}
     * @throws {@link PlanirApi.TooManyRequestsError}
     *
     * @example
     *     await client.runtimes.getEvents({
     *         id: "id"
     *     })
     */
    public getEvents(
        request: PlanirApi.GetEventsRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): core.HttpResponsePromise<PlanirApi.EventsList> {
        return core.HttpResponsePromise.fromPromise(this.__getEvents(request, requestOptions));
    }

    private async __getEvents(
        request: PlanirApi.GetEventsRuntimesRequest,
        requestOptions?: RuntimesClient.RequestOptions,
    ): Promise<core.WithRawResponse<PlanirApi.EventsList>> {
        const { id, cursor } = request;
        const _queryParams: Record<string, unknown> = {
            cursor,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlanirApiEnvironment.Default,
                `v1/runtimes/${core.url.encodePathParam(id)}/events`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PlanirApi.EventsList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlanirApi.BadRequestError(
                        _response.error.body as PlanirApi.InvalidRequestError,
                        _response.rawResponse,
                    );
                case 401:
                    throw new PlanirApi.UnauthorizedError(
                        _response.error.body as PlanirApi.UnauthenticatedError,
                        _response.rawResponse,
                    );
                case 403:
                    throw new PlanirApi.ForbiddenError(
                        _response.error.body as PlanirApi.TeamBlockedError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new PlanirApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new PlanirApi.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlanirApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/runtimes/{id}/events");
    }
}
