# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.regions_list import RegionsList
from .raw_client import AsyncRawRegionsClient, RawRegionsClient


class RegionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRegionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRegionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRegionsClient
        """
        return self._raw_client

    def list_regions(self, *, request_options: typing.Optional[RequestOptions] = None) -> RegionsList:
        """
        Every location on offer, with per-family `available` derived live — the picker's "can I order here now" truth. `region` values are plain strings (e.g. "brq"), never an enum: new locations appear additively; send one as `region` on create. `available` is probed with the family's smallest preset, so a larger preset's create may still refuse 503 at the capacity margin. Unavailable means full, draining, or not yet commissioned — a create naming that location refuses 503 until it flips (re-read rather than remember; no pagination, the list is a menu).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegionsList
            Every catalogued location, region-ASC.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.regions.list_regions()
        """
        _response = self._raw_client.list_regions(request_options=request_options)
        return _response.data


class AsyncRegionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRegionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRegionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRegionsClient
        """
        return self._raw_client

    async def list_regions(self, *, request_options: typing.Optional[RequestOptions] = None) -> RegionsList:
        """
        Every location on offer, with per-family `available` derived live — the picker's "can I order here now" truth. `region` values are plain strings (e.g. "brq"), never an enum: new locations appear additively; send one as `region` on create. `available` is probed with the family's smallest preset, so a larger preset's create may still refuse 503 at the capacity margin. Unavailable means full, draining, or not yet commissioned — a create naming that location refuses 503 until it flips (re-read rather than remember; no pagination, the list is a menu).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegionsList
            Every catalogued location, region-ASC.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.regions.list_regions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_regions(request_options=request_options)
        return _response.data
