# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_version_info import ApiVersionInfo
from .raw_client import AsyncRawMetaClient, RawMetaClient


class MetaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMetaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMetaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMetaClient
        """
        return self._raw_client

    def get_version(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiVersionInfo:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiVersionInfo
            The served API version.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.meta.get_version()
        """
        _response = self._raw_client.get_version(request_options=request_options)
        return _response.data


class AsyncMetaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMetaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMetaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMetaClient
        """
        return self._raw_client

    async def get_version(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiVersionInfo:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiVersionInfo
            The served API version.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meta.get_version()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_version(request_options=request_options)
        return _response.data
