// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface CreateRuntimesRequest {
    /** Optional client-supplied idempotency key. Same key + same body within the 24-hour replay window → 200 with the original runtime (not a new create); same key + different body → CONFLICT. Replay is the intended recovery path for a client that loses a runtime id after a 201: re-send the identical create and read the id back. Omitted = no idempotency claim — a retried create makes a second runtime. */
    "idempotency-key"?: string;
    body: PlanirApi.CreateRuntimeRequest;
}
