// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         image: "image"
 *     }
 */
export interface CreateRuntimeRequest {
    /** Optional client-supplied idempotency key. Same key + same body within the 24-hour replay window → 200 with the original runtime (not a new create); same key + different body → CONFLICT. Replay is the intended recovery path for a client that loses a runtime id after a 201: re-send the identical create and read the id back. Omitted = no idempotency claim — a retried create makes a second runtime. */
    "idempotency-key"?: string;
    /** Opaque client correlation handle. No shared id-space, no FK. Optional — the orchestrator generates one when omitted (echoed on reads). */
    clientRef?: string;
    /** Resolved container image ref the orchestrator pulls. MUST be anonymously pullable: no registry-credential channel exists (private registries are not supported). Echoed back on every Runtime read. */
    image: string;
    /** Optional opaque workload config, base64 over the wire (see the config description). Omitted = no config file is mounted at /etc/planir/config. */
    config?: string;
    /** Optional env vars (default {}). See the EnvMap description. */
    env?: Record<string, string>;
    /** Optional CMD override, Docker semantics (argv array, no shell). Omitted = the image's own CMD. Create-time only — there is no replace verb; recreate to change it. */
    command?: string[];
    /** Optional ENTRYPOINT override, Docker semantics (argv array, no shell). Omitted = the image's own ENTRYPOINT. Create-time only — there is no replace verb. */
    entrypoint?: string[];
    /** Optional resource allocation. Omitted = the published defaults: 1 vCPU (cpuMillis 1000), 2 GiB memoryBytes (2147483648), 4 GiB storageBytes (4294967296). Reads always echo the effective (defaults-applied) values. */
    resources?: CreateRuntimeRequest.Resources;
    /** Exposed ports the orchestrator routes the public handle to, as bare integers (e.g. [8080]). Omitted or [] = no public surface; never inferred from the image. Port numbers must be unique. */
    ports?: number[];
    /** Optional explicit HTTP readiness gate — `observed: running` then means this path answered. Omitted = a TCP probe on the FIRST declared port (or, with no declared ports, running = the container started). Exactly ONE probe ever. Create-time only — there is no replace verb. */
    readiness?: CreateRuntimeRequest.Readiness;
    /** Optional egress posture (see NetworkSpec). Omitted = open egress minus the standing SSRF/private deny. Replaceable later via PUT /network (applies live, no restart). */
    network?: CreateRuntimeRequest.Network;
    /** Optional correlation labels (default {}). See the metadata description. */
    metadata?: Record<string, string>;
    /** Hardening knob, default false. false (default): the rootfs is writable — a standard machine; writes land in the ephemeral scratch budget. true: the rootfs is the image verbatim, read-only, with writable /tmp and /run scratch mounts (funded by the same budget); anything durable belongs on `/data`. */
    rootfsReadOnly?: boolean;
    /** Initial desired state (default running). Cannot create destroyed. */
    desiredState?: CreateRuntimeRequest.DesiredState;
}

export namespace CreateRuntimeRequest {
    /**
     * Optional resource allocation. Omitted = the published defaults: 1 vCPU (cpuMillis 1000), 2 GiB memoryBytes (2147483648), 4 GiB storageBytes (4294967296). Reads always echo the effective (defaults-applied) values.
     */
    export interface Resources {
        /** RAM allocation in bytes. Minimum 134217728 (128 MiB) — below that no real image starts, so sub-floor requests are rejected here instead of surfacing as a confusing in-guest OOM after boot. */
        memoryBytes: number;
        /** CPU allocation in millicores (1000 = 1 vCPU). */
        cpuMillis: number;
        /** Persistent volume size in bytes. The volume is mounted read-write at `/data` inside the workload; it survives stop/start and follows the runtime for life. Writable by the workload's own user, whatever the image runs as — root or not, no setup needed: the volume root arrives group-writable to a platform group the workload process automatically carries as a supplementary group. Files the workload creates keep their normal ownership. Software that demands strict permissions on its data directory (e.g. PostgreSQL's initdb) should use a subdirectory and set its own mode (`mkdir -m 700 /data/pgdata`). This is the only metered disk. */
        storageBytes: number;
        /** Rootfs scratch-disk budget in bytes. The rootfs is a real block disk of a fixed tier size (4 or 8 GiB); the ask rounds UP to the smallest tier that fits, and `df /` inside the workload reports that tier honestly. Ephemeral: fresh from the image on every pod recreate; durable data belongs on `/data`. Bundled, never billed. Omitted → 4 GiB default. Free up to the 8 GiB cap; above the cap the request is rejected 422 — contact sales. Reads echo the requested value, never null. Filling the disk gives the writing process a plain ENOSPC write error — the workload keeps running; deleting files frees space immediately. */
        ephemeralStorageBytes?: number | undefined;
    }

    /**
     * Optional explicit HTTP readiness gate — `observed: running` then means this path answered. Omitted = a TCP probe on the FIRST declared port (or, with no declared ports, running = the container started). Exactly ONE probe ever. Create-time only — there is no replace verb.
     */
    export interface Readiness {
        /** Container port the HTTP readiness check hits. */
        port: number;
        /** HTTP path probed for readiness; 2xx/3xx = ready. */
        httpPath: string;
    }

    /**
     * Optional egress posture (see NetworkSpec). Omitted = open egress minus the standing SSRF/private deny. Replaceable later via PUT /network (applies live, no restart).
     */
    export interface Network {
        /** Allowlist mode when present: ONLY these destinations are reachable. Entries: IPv4 CIDRs or domain patterns (`*.` prefix wildcard). Domain rules follow DNS resolution — the documented industry limitation. */
        allowOut?: string[] | undefined;
        /** Destinations denied even when allowed (deny wins). IPv4 CIDRs ONLY — no platform on this substrate class denies by domain; use allowOut to constrain by domain. Alone (no allowOut): open egress minus these ranges. */
        denyOut?: string[] | undefined;
    }

    /** Initial desired state (default running). Cannot create destroyed. */
    export const DesiredState = {
        Running: "running",
        Stopped: "stopped",
    } as const;
    export type DesiredState = (typeof DesiredState)[keyof typeof DesiredState];
}
