// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             command: ["command"]
 *         }
 *     }
 */
export interface ExecRuntimesRequest {
    id: string;
    body: PlanirApi.ExecRequest;
}
