// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetEventsRuntimesRequest {
    id: string;
    /** Return only events whose cursor is strictly greater than this value. */
    cursor?: number | null;
}
