// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetLogsRuntimesRequest {
    id: string;
    /** `true` reads the PRIOR container's tail after a crash/restart — the dying breath a crash-looping workload never shows in its live logs. */
    previous?: PlanirApi.GetLogsRuntimesRequestPrevious;
}
