// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListRuntimesRequest {
    /** Page size, 1–100 (default 20). */
    limit?: number;
    /** Opaque page cursor — pass the previous page's `nextCursor` verbatim. Omitted = from the start. */
    cursor?: string;
    /** Destroyed runtimes are excluded unless this is `true`. Ignored when an explicit `desiredState` filter is present (that filter fully determines state visibility). */
    includeDestroyed?: PlanirApi.ListRuntimesRequestIncludeDestroyed;
    /** Repeatable desired-state filter (`running|stopped|destroyed`): OR within the repeated values, AND with the metadata filters. When present it fully determines state visibility — `?desiredState=destroyed` returns destroyed runtimes without `includeDestroyed`. Absent = destroyed excluded unless `includeDestroyed=true`. */
    desiredState?: PlanirApi.ListRuntimesRequestDesiredStateItem | PlanirApi.ListRuntimesRequestDesiredStateItem[];
    /** Equality filter on the home location — the `region` every response echoes (ANDs with the other filters). A value no runtime carries returns an empty page, never an error (discovery: GET /v1/regions). */
    region?: string;
}
