// This file was auto-generated by Fern from our API Definition.

import type * as PlanirApi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         network: {}
 *     }
 */
export interface NetworkRequest {
    id: string;
    network: PlanirApi.NetworkSpec;
}
