// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         port: 1
 *     }
 */
export interface ReachRequest {
    id: string;
    /** The internal port to resolve. The caller always names it. */
    port: number;
}
