// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         amountMicrocents: 1,
 *         successUrl: "successUrl",
 *         cancelUrl: "cancelUrl"
 *     }
 */
export interface TopupRequest {
    /** Credit to add, in USD integer microcents (1 USD = 100,000,000). A whole number of US cents (a multiple of 1,000,000), between $1 (100,000,000) and $100,000 (10,000,000,000,000). The balance is credited with what Stripe actually charges, not this requested value. */
    amountMicrocents: number;
    /** Absolute URL Stripe returns the payer to after a completed payment. */
    successUrl: string;
    /** Absolute URL Stripe returns the payer to if they abandon the payment. */
    cancelUrl: string;
}
