# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.volume import Volume
from ..types.volumes_list import VolumesList
from .raw_client import AsyncRawVolumesClient, RawVolumesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VolumesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVolumesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVolumesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVolumesClient
        """
        return self._raw_client

    def list_volumes(self, *, request_options: typing.Optional[RequestOptions] = None) -> VolumesList:
        """
        Every volume the team owns, standalone AND runtime-managed (`deleteWithRuntime: true` rows are the auto-created `/data` volumes, named `data-<runtimeId>`) — one storage model, two lifecycles.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumesList
            The team's volumes.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.volumes.list_volumes()
        """
        _response = self._raw_client.list_volumes(request_options=request_options)
        return _response.data

    def create_volume(
        self,
        *,
        name: str,
        size_bytes: int,
        region: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Volume:
        """
        Provisions the backing storage fully or leaves nothing (create saga) — a 201 means the volume exists and its size is the device-enforced hard cap. Born `available`; attach it by creating a runtime with `volumeId`. The volume is homed in a location at create (optional `region`, the same choice runtime create takes; the response echoes it) and stays there for life — a runtime attaching it is placed there. Billing accrues provisioned byte-seconds from create to delete, attached or not — so metered admission gates here exactly as on runtime create: a non-positive balance is a 402.

        Parameters
        ----------
        name : str
            The human handle, unique within the team (duplicate → 409 CONFLICT). Lowercase DNS-label shape: `[a-z0-9]` with interior hyphens, 1–63 chars. Names beginning `data-` are reserved for runtime-managed `/data` volumes (400).

        size_bytes : int
            Provisioned size in bytes — a hard cap enforced by the device itself (the workload hits plain ENOSPC at the brim; deleting files frees space immediately). Fixed for the volume's life (no resize in v1). Billed as provisioned byte-seconds from create to delete, attached or not.

        region : typing.Optional[str]
            The location to home the volume in — the same choice runtime create takes. Omitted: the default location. A location that is not offered → 422; one with no capacity right now → 503 (nothing provisioned). See `GET /v1/regions`. The home is fixed for the volume's life: a runtime attaching this volume is placed here (data gravity — the runtime follows the volume, never the reverse).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Volume
            The volume, born `available`.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.volumes.create_volume(
            name="name",
            size_bytes=1,
        )
        """
        _response = self._raw_client.create_volume(
            name=name, size_bytes=size_bytes, region=region, request_options=request_options
        )
        return _response.data

    def get_volume(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Volume:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Volume
            The volume.

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.volumes.get_volume(
            id="id",
        )
        """
        _response = self._raw_client.get_volume(id, request_options=request_options)
        return _response.data

    def delete_volume(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Removes the backing storage and ends billing at this instant. Only an `available` volume can be deleted: an attached one is held for its runtime's whole life (stopped included) — destroy the runtime first. The data is unrecoverable.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from planir import PlanirClient

        client = PlanirClient(
            token="YOUR_TOKEN",
        )
        client.volumes.delete_volume(
            id="id",
        )
        """
        _response = self._raw_client.delete_volume(id, request_options=request_options)
        return _response.data


class AsyncVolumesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVolumesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVolumesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVolumesClient
        """
        return self._raw_client

    async def list_volumes(self, *, request_options: typing.Optional[RequestOptions] = None) -> VolumesList:
        """
        Every volume the team owns, standalone AND runtime-managed (`deleteWithRuntime: true` rows are the auto-created `/data` volumes, named `data-<runtimeId>`) — one storage model, two lifecycles.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VolumesList
            The team's volumes.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.volumes.list_volumes()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_volumes(request_options=request_options)
        return _response.data

    async def create_volume(
        self,
        *,
        name: str,
        size_bytes: int,
        region: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Volume:
        """
        Provisions the backing storage fully or leaves nothing (create saga) — a 201 means the volume exists and its size is the device-enforced hard cap. Born `available`; attach it by creating a runtime with `volumeId`. The volume is homed in a location at create (optional `region`, the same choice runtime create takes; the response echoes it) and stays there for life — a runtime attaching it is placed there. Billing accrues provisioned byte-seconds from create to delete, attached or not — so metered admission gates here exactly as on runtime create: a non-positive balance is a 402.

        Parameters
        ----------
        name : str
            The human handle, unique within the team (duplicate → 409 CONFLICT). Lowercase DNS-label shape: `[a-z0-9]` with interior hyphens, 1–63 chars. Names beginning `data-` are reserved for runtime-managed `/data` volumes (400).

        size_bytes : int
            Provisioned size in bytes — a hard cap enforced by the device itself (the workload hits plain ENOSPC at the brim; deleting files frees space immediately). Fixed for the volume's life (no resize in v1). Billed as provisioned byte-seconds from create to delete, attached or not.

        region : typing.Optional[str]
            The location to home the volume in — the same choice runtime create takes. Omitted: the default location. A location that is not offered → 422; one with no capacity right now → 503 (nothing provisioned). See `GET /v1/regions`. The home is fixed for the volume's life: a runtime attaching this volume is placed here (data gravity — the runtime follows the volume, never the reverse).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Volume
            The volume, born `available`.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.volumes.create_volume(
                name="name",
                size_bytes=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_volume(
            name=name, size_bytes=size_bytes, region=region, request_options=request_options
        )
        return _response.data

    async def get_volume(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Volume:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Volume
            The volume.

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.volumes.get_volume(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_volume(id, request_options=request_options)
        return _response.data

    async def delete_volume(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Removes the backing storage and ends billing at this instant. Only an `available` volume can be deleted: an attached one is held for its runtime's whole life (stopped included) — destroy the runtime first. The data is unrecoverable.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from planir import AsyncPlanirClient

        client = AsyncPlanirClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.volumes.delete_volume(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_volume(id, request_options=request_options)
        return _response.data
